### ISSUE TITLE
Can Aeon be used in the US?

### ISSUE THREAD

**Issue by Darth-Ness** [leinelissen/aeon#332]
This is a really cool project!

However, I live in the US, so if it only works it in the Europe then I obviously can't use it.

**Comment by leinelissen** [comment]
Hey there! This is a great question. This depends on whether you make use of the automated data gathering (for Facebook, Twitter, LinkedIn and Spotify) or want to send out manual (email-based) requests. As for automated gathering, the good news is that these platforms offer data access services worldwide regardless of legal mandates. You can just start Aeon and start retrieving this data. 

The manual requests however, really depend on legislation on which you can build your claim. These are most straightforward if you're an EU citizen. There are options if you're not a EU citizen, but this depends on local legislation and sometimes state law as well. For instance, the [California Consumer Privacy Act](https://en.wikipedia.org/wiki/California_Consumer_Privacy_Act) affords nearly similar rights as the GDPR to Californians. From what I can quickly gather, laws modeled on the CCPA have been passed in at least Virginia, Colorado and Utah. 

Laws based on the GDPR have been passed in at least Israel, Turkey, Canada, South Africa, New Zealand, South Korea, Brazil and Argentina, among others.

**Comment by Darth-Ness** [comment]
> Hey there! This is a great question. This depends on whether you make use of the automated data gathering (for Facebook, Twitter, LinkedIn and Spotify) or want to send out manual (email-based) requests. As for automated gathering, the good news is that these platforms offer data access services worldwide regardless of legal mandates. You can just start Aeon and start retrieving this data.
> 
> The manual requests however, really depend on legislation on which you can build your claim. These are most straightforward if you're an EU citizen. There are options if you're not a EU citizen, but this depends on local legislation and sometimes state law as well. For instance, the [California Consumer Privacy Act](https://en.wikipedia.org/wiki/California_Consumer_Privacy_Act) affords nearly similar rights as the GDPR to Californians. From what I can quickly gather, laws modeled on the CCPA have been passed in at least Virginia, Colorado and Utah.
> 
> Laws based on the GDPR have been passed in at least Turkey, South Africa, South Korea, Chile and Argentina, among others.

Okay thank you.
