### ISSUE TITLE
Add email functionality not working

### ISSUE THREAD

**Issue by yaelvalle** [leinelissen/aeon#368]
Whenever I try to add my email nothing happens, the window responds by acting like the focus is being taken away from it but no other window or prompt appears

**Comment by leinelissen** [comment]
Hi there @yaelvalle. Yes that's right, I am working on a new release but I couldn't get it out before the holidays. I'll try and release it this week, then you can try it out ;)

**Comment by leinelissen** [comment]
Hi there, I'm back again. I've just published `v0.2.21` which should include a fix for this problem. The auto-updater should pick it up shortly, and if it doesn't, you can find the new version here: https://github.com/leinelissen/aeon/releases/tag/v0.2.21. Please report back if this fixes your issue and with any further feedback :)
